### ISSUE TITLE
qtum hd wallet path is ?

### ISSUE THREAD

**Issue by qianjin** [qtumproject/qtum-web-wallet#12]
we create a qtum wallet use path : m/44'/2301'/0'/88'/0'  the address like not right , then we try  m/44'/2301'/88'/0'/0' and m/44'/2301'/88'/0' also not right...

**Comment by qianjin** [comment]
why is m/88'/0'/0'/ and m/88'/0'/  , in the bip44 you define your coin is 2301'..

**Comment by qtumweiyu** [comment]
the 2301 is not defined by us in the bip44

**Comment by icodeface** [comment]
@qtumweiyu qtum electrum uses m/44'/88'/0'/0' but not m/88'/0'/0' like the web wallet.

**Comment by qianjin** [comment]
@icodeface m/44'/88'/0'/0' is error , I test it is m/88'/0'/0' when has password , m/88'/0' when not has password,
the code in web wallet can find.

![qq 20180427092938](https://user-images.githubusercontent.com/1849426/39339901-a93000ae-49fd-11e8-9773-59d9d85b9e45.png)

**Comment by qtumweiyu** [comment]
close
