### ISSUE TITLE
Successful notice should be noticeable and clickable

### ISSUE THREAD

**Issue by Baiqiang** [qtumproject/qtum-web-wallet#21]
Currently there's only a small green bar on the bottom of the page and it will disappear after seconds. This is not friendly for users. The link on it even can't be clicked.
![image](https://user-images.githubusercontent.com/2390434/43253219-093cf7f0-90f7-11e8-987a-83c83c9f471f.png)

BTW, please change Qtum Explorer to https://qtum.info

**Comment by pasDamola** [comment]
hi @Baiqiang can i take this up?? and how do i reproduce this issue??

**Comment by Baiqiang** [comment]
@pasDamola I think this has been (partly) resolved. I'm going to close this issue.
